package com.bcdata.shortlink.component;

import com.bcdata.shortlink.entity.ShortLink;
import com.bcdata.shortlink.entity.ShortLinkRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cache.CacheManager;
import org.springframework.cache.annotation.CachePut;
import org.springframework.cache.annotation.Cacheable;

import javax.annotation.PostConstruct;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * cache for short link
 *
 * @author yuxuecheng
 * @version 1.0
 * @contact yuxuecheng@baicdata.com
 * @time 2018 May 21 13:35
 */
public class ShortLinkCache {

    private static Logger logger = LoggerFactory.getLogger (ShortLinkCache.class);

    private Map<String, ShortLink> shortLinkCache = new HashMap<> ();

    @Autowired // This means to get the bean called shortLinkRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private ShortLinkRepository shortLinkRepository;

    @Autowired
    private CacheManager cacheManager;

    /**
     * 初始化
     */
    @PostConstruct
    public void Init() {
        List<ShortLink> results = shortLinkRepository.findAll ();
        for (ShortLink shortLink : results) {
            logger.info ("init short for uri: " + shortLink.getUri ());
            ;
            shortLinkCache.put (shortLink.getUri (), shortLink);
        }
    }
}
